[project]
name = "token-lens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "fastapi>=0.115.8",
    "torch==2.5.1",
    "transformers>=4.49.0",
    "uvicorn>=0.34.0",
    "vllm>=0.7.3"
]
